version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    restart: unless-stopped