version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8080
      - JWT_SECRET=your_secure_jwt_secret_here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5