version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Changed from 5000 to 8080 for Azure compatibility
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
    environment:
      - NODE_ENV=production  # Set to production for optimized performance
      - PORT=8080  # Ensure the application listens on the correct port
      - DEBUG=true  # Enable debugging logs for troubleshooting
      - LOG_LEVEL=info  # Standardized logging level
    restart: unless-stopped  # Ensures the container restarts on failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # Checks if the app is running
      interval: 30s
      timeout: 10s
      retries: 5
