name: CCA-CF Survey App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          cd server
          npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Create Environment Files
        run: |
          echo "PORT=8080" > .env
          echo "NODE_ENV=production" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Install Production Dependencies
        run: |
          npm ci --omit=dev
          cd server
          npm ci --omit=dev

      - name: Create Deployment Artifact
        run: |
          zip -r release.zip . \
            -x "*.git*" \
            -x "*.github*" \
            -x "node_modules/*" \
            -x "server/node_modules/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Unzip Artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cca-cf-survey'
          package: .

      - name: Verify Deployment
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://cca-cf-survey.azurewebsites.net)
          if [ $response -ne 200 ]; then
            echo "Deployment verification failed with status $response"
            exit 1
          fi
