name: Build and deploy Node.js app to Azure Web App - cca-cf-survey
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug - Show directory contents
        run: |
          echo "Current directory contents:"
          ls -la
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Create package.json if missing
        run: |
          if [ ! -f "package.json" ]; then
            echo "Creating package.json file..."
            cat > package.json << 'EOL'
            {
              "name": "cca-cf-survey",
              "version": "1.0.0",
              "description": "CCA-CF Survey Application",
              "main": "server/app.js",
              "scripts": {
                "start": "node server/start.js"
              },
              "engines": {
                "node": ">=18.0.0",
                "npm": ">=9.0.0"
              },
              "dependencies": {
                "bcryptjs": "^3.0.2",
                "cors": "^2.8.5",
                "dotenv": "^16.4.7",
                "express": "^4.21.2",
                "jsonwebtoken": "^9.0.2",
                "helmet": "^7.1.0",
                "winston": "^3.11.0",
                "express-rate-limit": "^7.1.5"
              }
            }
            EOL
            echo "Created package.json"
          else
            echo "package.json already exists"
          fi
          
      - name: Install dependencies
        run: npm install
        
      - name: Install server dependencies
        run: |
          if [ -d "server" ] && [ -f "server/package.json" ]; then
            cd server
            npm install --production
            cd ..
          fi
      
      - name: Create .deployment file
        run: |
          echo "[config]" > .deployment
          echo "command = npm start" >> .deployment
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "node_modules/*" "*.git*" "*.github/*" "*/.vscode/*"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9BBBDCA60F0E4D9B96094EFB4BCC1302 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1FDAA4C26E649A19CBAACE111D486A9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C4187E6C596F4D8B9A0819B05E467CCA }}
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cca-cf-survey'
          slot-name: 'Production'
          package: .
