name: CCA-CF Survey Server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Linter
        run: npm run lint
      
      - name: Run Tests
        run: npm test || echo "No tests configured"

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'

      - name: Create Environment Files
        run: |
          echo "PORT=8080" > .env
          echo "NODE_ENV=production" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Install Production Dependencies
        run: npm ci --omit=dev

      - name: Create Deployment Artifact
        run: |
          mkdir -p ../artifact
          cp -r . ../artifact/
          cp ../.env ../artifact/
          cd ..
          zip -r release.zip artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-release
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://cca-cf-survey.azurewebsites.net
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: server-release

      - name: Unzip Artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cca-cf-survey'
          package: artifact

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30
          response=$(curl -s -o /dev/null -w "%{http_code}" https://cca-cf-survey.azurewebsites.net/health)
          if [ $response -ne 200 ]; then
            echo "Deployment verification failed with status $response"
            exit 1
          fi

  security-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
